services:
  i2pd:
    build:
      context: ./i2p
    restart: unless-stopped
    environment:
      ENABLE_TUNNELS: 1
    # TODO: This only works when the network is private
    ports:
      - 7070:7070
      - 4444:4444
      - 4445:4445

  reseed:
    # TODO: pin this for reproducability
    image: mkuettel/i2p-reseed:latest
    environment:
      - SIGNER=mkuettel@mail.i2p
    ports:
      - 8443


  selftest:
    image: ubuntu:20.10
