version: "3.8"
services:
  i2pd:
    environment:
      - RESEED_WAIT_URL=http://10.23.0.1:8443/i2pseeds.su3
    ports:
      - 7070:7070
      - 4445:4445
  reseed:
    # TODO: pin this for reproducability
    image: mkuettel/i2p-reseed:latest
    ports:
      - 8443
    volumes:
      # RELATIVE to the docker-compose file!
      - ./docker/volumes/reseed-netDb:/home/i2preseed/netDb
    environment:
      - SIGNER=mkuettel@mail.i2p
      - WAIT_ROUTER_INFOS_COLLECTED=1
    networks:
      i2ptestnet:
        ipv4_address: 10.23.0.1
